In [1]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import pandas as pd
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from konlpy.tag import Okt
import nltk
import koreanize_matplotlib

okt = Okt()
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
df = pd.read_csv('csv/test.csv')

In [3]:
import re

def remove_special_characters(text):
    # 이모티콘 및 특수문자 제거를 위한 정규표현식
    pattern = r'[^a-zA-Z0-9가-힣\s]'  # 영문, 한글, 숫자, 공백만 허용

    # 정규표현식을 사용하여 특수문자 제거
    cleaned_text = re.sub(pattern, '', text)
    return cleaned_text

# '내용' 열의 각 행에 대해 이모티콘과 특수문자 제거
df['contents'] = df['내용'].dropna().apply(remove_special_characters)

In [4]:
df[['내용','contents']]

내용  \
0    2024년 취업가능! 항공 데이터 전문가 양성과정\n💻7기 선착순 모집중\n\n_2...   
1    2024년 "日本, JAVA 및 ICT 전문가 양성과정(7기)" 연수생을 모집합니다...   
2    2024년 백엔드 취업까지 걸리는 시간\n단, 6개월\n\n테킷 백엔드 스쿨은\nJ...   
3    📢 Java 기반 DevOps 개발자 양성과정 훈련생 모집\n\n#개발 과 #운영 ...   
4    👨‍💻 IT 개발자 필수 채용정보. ZIP\n\n👉print(“Hello, IT개발...   
..                                                 ...   
415  🚨 백엔드 부트캠프 시작 전 체크리스트 🚨\n'누가' '무엇을' 알려주는지 꼭 확인...   
416  🚨 백엔드 부트캠프 시작 전 체크리스트 🚨\n'누가' '무엇을' 알려주는지 꼭 확인...   
417  부트캠프 선택 전 '누가' '무엇을' 알려주는지 꼭 확인하세요!\n백엔드 스쿨은 백...   
418  🎊 마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시!\n마케팅 취업교육...   
419  🎊 마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시!\n마케팅 취업교육...   

                                              contents  
0    2024년 취업가능 항공 데이터 전문가 양성과정\n7기 선착순 모집중\n\n24년 ...  
1    2024년  JAVA 및 ICT 전문가 양성과정7기 연수생을 모집합니다\n\n한국산...  
2    2024년 백엔드 취업까지 걸리는 시간\n단 6개월\n\n테킷 백엔드 스쿨은\nJa...  
3     Java 기반 DevOps 개발자 양성과정 훈련생 모집\n\n개발 과 운영 을 동...  
4     IT 개발자 필수 채용정보 ZIP\n\nprintHello IT개발자\n개발자 취...  
..                                                 ...  
415   백엔드 부트캠프 시작 전 체크리스트 \n누가 무엇을 알려주는지 꼭 확인하세요\n\...  
416   백엔드 부트캠프 시작 전 체크리스트 \n누가 무엇을 알려주는지 꼭 확인하세요\n\...  
417  부트캠프 선택 전 누가 무엇을 알려주는지 꼭 확인하세요\n백엔드 스쿨은 백준과 함께...  
418   마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시\n마케팅 취업교육 원...  
419   마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시\n마케팅 취업교육 원...  

[420 rows x 2 columns]

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# 예시 데이터
corpus = df['contents'].dropna().tolist()

# CountVectorizer 초기화
vectorizer = CountVectorizer()

# 텍스트 데이터를 벡터로 변환
X = vectorizer.fit_transform(corpus)

# 벡터화된 결과를 배열로 변환
vectorized_data = X.toarray()

# 단어 목록
words = vectorizer.get_feature_names_out()

# 결과 출력
print("Words:", words)
print("Vectorized Data:")
print(vectorized_data)

Words: ['01' '010' '01055574228' ... '희망한다면' '힘들고' '힘들었을']
Vectorized Data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
words

array(['01', '010', '01055574228', ..., '희망한다면', '힘들고', '힘들었을'],
      dtype=object)

In [7]:
import re

# 예시 데이터


# 숫자를 제외한 부분을 추출하여 새로운 리스트 생성
result_list = [re.sub(r'\d', '', item) for item in words]

result_list = [item for item in words if item != '']
# 결과 출력

# 숫자가 4개 미만인 문자열을 추출하여 새로운 리스트 생성
result_list2 = [item for item in words if sum(c.isdigit() for c in item) < 4]


print(result_list2)

['01', '010', '01일', '04월', '05년생', '06배수', '07월', '0원', '0원에', '0원으로', '10', '100', '100가지', '100개', '100로', '100명', '100인', '100종부터', '100취업보장', '10개', '10개월', '10년', '10년간', '10년이상', '10년차', '10년차이자', '10년치의', '10명', '10명만', '10월말', '10일', '10일간만', '10일을', '10자리를', '10주', '11', '11개', '11대비', '11로', '11월', '11일', '11일까지', '11취업지원팀', '11컨설팅', '124건의', '125', '125만', '12개의', '12년', '12번의', '12시간', '12일', '13가지', '13개소만', '14기', '14만', '150만', '158개의', '15년', '15인이', '160시간의', '160종', '16일', '17년간', '17시', '18기', '18일', '19일', '1개월', '1기', '1기생', '1년', '1년간', '1달마다', '1도', '1시', '1시간만', '1월', '1위', '1일', '1주일', '1차면접', '1천만', '20', '200명', '20개', '20만', '20만원월', '20명', '20종', '219', '21명', '226월', '228', '229목', '23일', '23학번', '24년', '24명', '24시간', '25', '25개를', '25일', '27주년을', '28일', '29일', '2강의를', '2개를', '2개월', '2기', '2기를', '2년', '2년만에', '2월', '2일', '2차면접', '2학기', '30만원', '30명', '30분', '30분이면', '30여년', '30일', '311', '316만', '316만원', '31금', '31만', '31만6천원', '31월과', '321', '32기', '32주'

In [8]:
result_list2

['01',
 '010',
 '01일',
 '04월',
 '05년생',
 '06배수',
 '07월',
 '0원',
 '0원에',
 '0원으로',
 '10',
 '100',
 '100가지',
 '100개',
 '100로',
 '100명',
 '100인',
 '100종부터',
 '100취업보장',
 '10개',
 '10개월',
 '10년',
 '10년간',
 '10년이상',
 '10년차',
 '10년차이자',
 '10년치의',
 '10명',
 '10명만',
 '10월말',
 '10일',
 '10일간만',
 '10일을',
 '10자리를',
 '10주',
 '11',
 '11개',
 '11대비',
 '11로',
 '11월',
 '11일',
 '11일까지',
 '11취업지원팀',
 '11컨설팅',
 '124건의',
 '125',
 '125만',
 '12개의',
 '12년',
 '12번의',
 '12시간',
 '12일',
 '13가지',
 '13개소만',
 '14기',
 '14만',
 '150만',
 '158개의',
 '15년',
 '15인이',
 '160시간의',
 '160종',
 '16일',
 '17년간',
 '17시',
 '18기',
 '18일',
 '19일',
 '1개월',
 '1기',
 '1기생',
 '1년',
 '1년간',
 '1달마다',
 '1도',
 '1시',
 '1시간만',
 '1월',
 '1위',
 '1일',
 '1주일',
 '1차면접',
 '1천만',
 '20',
 '200명',
 '20개',
 '20만',
 '20만원월',
 '20명',
 '20종',
 '219',
 '21명',
 '226월',
 '228',
 '229목',
 '23일',
 '23학번',
 '24년',
 '24명',
 '24시간',
 '25',
 '25개를',
 '25일',
 '27주년을',
 '28일',
 '29일',
 '2강의를',
 '2개를',
 '2개월',
 '2기',
 '2기를',
 '2년',
 '2년만에',
 '2월',
 '2일',
 '2차면접',
 '2학기',
 '30만