In [3]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import pandas as pd
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from konlpy.tag import Okt
import nltk
import koreanize_matplotlib

okt = Okt()
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
df = pd.read_csv('csv/test.csv')

In [7]:
import re

def remove_special_characters(text):
    # 이모티콘 및 특수문자 제거를 위한 정규표현식
    pattern = r'[^a-zA-Z0-9가-힣\s]'  # 영문, 한글, 숫자, 공백만 허용

    # 정규표현식을 사용하여 특수문자 제거
    cleaned_text = re.sub(pattern, '', text)
    return cleaned_text

# '내용' 열의 각 행에 대해 이모티콘과 특수문자 제거
df['contents'] = df['내용'].dropna().apply(remove_special_characters)

In [9]:
df[['내용','contents']]

내용  \
0    2024년 취업가능! 항공 데이터 전문가 양성과정\n💻7기 선착순 모집중\n\n_2...   
1    2024년 "日本, JAVA 및 ICT 전문가 양성과정(7기)" 연수생을 모집합니다...   
2    2024년 백엔드 취업까지 걸리는 시간\n단, 6개월\n\n테킷 백엔드 스쿨은\nJ...   
3    📢 Java 기반 DevOps 개발자 양성과정 훈련생 모집\n\n#개발 과 #운영 ...   
4    👨‍💻 IT 개발자 필수 채용정보. ZIP\n\n👉print(“Hello, IT개발...   
..                                                 ...   
415  🚨 백엔드 부트캠프 시작 전 체크리스트 🚨\n'누가' '무엇을' 알려주는지 꼭 확인...   
416  🚨 백엔드 부트캠프 시작 전 체크리스트 🚨\n'누가' '무엇을' 알려주는지 꼭 확인...   
417  부트캠프 선택 전 '누가' '무엇을' 알려주는지 꼭 확인하세요!\n백엔드 스쿨은 백...   
418  🎊 마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시!\n마케팅 취업교육...   
419  🎊 마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시!\n마케팅 취업교육...   

                                              contents  
0    2024년 취업가능 항공 데이터 전문가 양성과정\n7기 선착순 모집중\n\n24년 ...  
1    2024년  JAVA 및 ICT 전문가 양성과정7기 연수생을 모집합니다\n\n한국산...  
2    2024년 백엔드 취업까지 걸리는 시간\n단 6개월\n\n테킷 백엔드 스쿨은\nJa...  
3     Java 기반 DevOps 개발자 양성과정 훈련생 모집\n\n개발 과 운영 을 동...  
4     IT 개발자 필수 채용정보 ZIP\n\nprintHello IT개발자\n개발자 취...  
..                                                 ...  
415   백엔드 부트캠프 시작 전 체크리스트 \n누가 무엇을 알려주는지 꼭 확인하세요\n\...  
416   백엔드 부트캠프 시작 전 체크리스트 \n누가 무엇을 알려주는지 꼭 확인하세요\n\...  
417  부트캠프 선택 전 누가 무엇을 알려주는지 꼭 확인하세요\n백엔드 스쿨은 백준과 함께...  
418   마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시\n마케팅 취업교육 원...  
419   마케팅 취업교육 사전 설명회\n9월 10일 일요일 오후 8시\n마케팅 취업교육 원...  

[420 rows x 2 columns]

# TF - IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 문장 리스트
sentences = df['contents'].dropna().tolist()

# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(sentences)

# 특정 키워드의 TF-IDF 값을 확인
keyword_index = vectorizer.vocabulary_['빅데이터']
tfidf_values = tfidf_matrix[:, keyword_index].toarray().flatten()

# 각 문장에서의 TF-IDF 값 출력
for i, sentence in enumerate(sentences):
    if tfidf_values[i] > 0:
        print(f"Sentence {i + 1}: {sentence}, TF-IDF: {tfidf_values[i]}")

Sentence 13: KDigital Training 빅데이터 분석가되자

조기 마감 주의
개인별 고사양 노트북 제공
수업만 잘 들어도 매월 최대 316만원 지급
대기업 중견소속 멘토가 직접 지도해주는 최종프로젝트 멘토링

 교육기간
 2024년 04월 11일 2024년 9월 12일
월금 오전 9시  오후 6시

 신청대상
 빅데이터 분야로 진출하고자 하는 자로 교육 수료 후 6개월 이내 취업이 가능한 자
 IT 및 SW분야와 통계학 등의 관련 전공자와 빅데이터 분석에 대한 개념을 이해하는자

우대요건
빅데이터 개발분석시각화 등의 공모전 등의 입상자
관련학과 전공자 및 관련 분야 경험자
데이터 관련 타 교육 프로그램 수료자
PythonSQLNoSQLCCJAVA 등 기초적인 프로그래밍 언어 활용이 가능한 자

 혜택
1 교육비 전액 무료  교재 및 다과 제공
2 훈련장려금 지원월 최대 316000원
3 기업 현장 전문가가 최종프로젝트의 각 팀 멘토로 참여
4 실제 해당 분야 현업전문가가 참여하는 특강
5 현장 전문가가 직접 참여하는 모의 면접

 문의
Tel  0707525856807075258908
Email  cnk0513medicieducokr
knr9712medicieducokr, TF-IDF: 0.28336333632281135
Sentence 14: KDigital Training 빅데이터 분석가되자

조기 마감 주의
개인별 고사양 노트북 제공
수업만 잘 들어도 매월 최대 316만원 지급
대기업 중견소속 멘토가 직접 지도해주는 최종프로젝트 멘토링

 교육기간
 2024년 04월 11일 2024년 9월 12일
월금 오전 9시  오후 6시

 신청대상
 빅데이터 분야로 진출하고자 하는 자로 교육 수료 후 6개월 이내 취업이 가능한 자
 IT 및 SW분야와 통계학 등의 관련 전공자와 빅데이터 분석에 대한 개념을 이해하는자

우대요건
빅데이터 개발분석시각화 등의 공모전 등의 입상자
관련학과 전공자 및 관련 분야 경험자
데이터 관련 타 교육 프로그램 수료자


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 예시 데이터
keywords = df[df['검색어'] == '빅데이터']
contents = df['contents'].dropna().tolist()
# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([*keywords, *contents])

# 키워드와 컨텐츠 간의 코사인 유사도 계산
cosine_similarities = cosine_similarity(tfidf_matrix)

# 결과 출력
print("Cosine Similarities:")
print(cosine_similarities)

Cosine Similarities:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]
